name: stepone

on:
  push:
    branches:
      - prompting

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:

      - name: should prompt
        run: echo "did the env rule prompt?"
