name: static-website

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Deploy Homepage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.MYKEY }}
        aws-secret-access-key: ${{ secrets.MYSECRET }}
        aws-region: ap-southeast-2
          
    - name: Copy to shopcart bucket.
      run: |
        aws s3 sync ./ s3://shopcart.craiggunson.com --acl public-read --cache-control "max-age=60" --delete
