
name: Build and Deploy to Google

on:
  push:
    branches: [ "actions" ]

env:
  PROJECT_ID: ${{ secrets.THIS_PROJECT }}

jobs:
  setup-build-publish-deploy:
    name: Copy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Copy
      run: |-
        gcloud version
        node --version
        npm --version
        gsutil -h "Content-Type:text/html" -h "Cache-Control: max-age=60" cp *.html gs://cart.craiggunson.com
        gsutil -h "Content-Type:text/css" -h "Cache-Control: max-age=60" cp *.css gs://cart.craiggunson.com
        gsutil -h "Content-Type:font/ttf" -h "Cache-Control: max-age=60" cp *.ttf gs://cart.craiggunson.com
        gsutil -h "Content-Type:text/javascript" -h "Cache-Control: max-age=60" cp *.js gs://cart.craiggunson.com

        gsutil ls gs://cart.craiggunson.com